# `numpy`
## A multidimensional array framework and more

In [1]:
import numpy as np

In [2]:
A = np.zeros((10,5)) # create an array filled with zeros
A

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [3]:
A.dtype # default data type is f8, aka double-precision floating point (8 bytes per number)

dtype('float64')

In [4]:
B = np.zeros((10,5), dtype='i4') # 4 byte (32 bit) integer

In [5]:
B.dtype

dtype('int32')

Some common data types:
- `f` floating-point number: `f4` single precision, `f8` double precision
- `i` (signed) integer number: `i4` 32-bit integer, `i8` 64-bit integer
- `u` unsigned integer
- `c` complex floating-point: `c16` double-precision for real and imaginary part
- `S` string
- `O` arbitrary Python objects (inefficent but flexible)

Arrays can be initialized using anything iterable. Most commonly this is a (nested) list.

In [6]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
C[0,2] # indices always start at 0

3

### Array Operations
Many operators are overloaded so that operations are applied element-wise.

In [8]:
2 * C

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
C + C**2

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [10]:
C + C.T # .T transposes the array

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

### Shapes
Arrays can easily be flattened (converted to 1D) or reshaped, provided that the total size does not change.

In [11]:
C.shape

(3, 3)

In [12]:
C.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
D = np.arange(20) # like range but returns an array instead of an iterator
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
D.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Broadcasting
For operations between two arrays to succeed the corresponding dimensions have to be equal or one of them has to be one. In the latter case the size-one dimension is broadcast over the entries of the other array in that dimension.

In [15]:
E = np.array([10, 20, 30])

In [16]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
E

array([10, 20, 30])

In [18]:
C + E

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

To facilitate efficient broadcasting, empty dimensions can be inserted using `None`.

In [19]:
F = E[None,:]

In [20]:
F

array([[10, 20, 30]])

In [21]:
C + F

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

Broadcasting can create large arrays from 1D arrays.

For example, compute radius on a 2D grid from 1D coordinate arrays.

In [22]:
X = np.arange(10)[:,None]
Y = np.arange(10)[None,:]

In [23]:
X.shape, Y.shape

((10, 1), (1, 10))

In [24]:
(X**2 + Y**2).shape

(10, 10)

In [25]:
np.sqrt(X**2 + Y**2)

array([[  0.        ,   1.        ,   2.        ,   3.        ,
          4.        ,   5.        ,   6.        ,   7.        ,
          8.        ,   9.        ],
       [  1.        ,   1.41421356,   2.23606798,   3.16227766,
          4.12310563,   5.09901951,   6.08276253,   7.07106781,
          8.06225775,   9.05538514],
       [  2.        ,   2.23606798,   2.82842712,   3.60555128,
          4.47213595,   5.38516481,   6.32455532,   7.28010989,
          8.24621125,   9.21954446],
       [  3.        ,   3.16227766,   3.60555128,   4.24264069,
          5.        ,   5.83095189,   6.70820393,   7.61577311,
          8.54400375,   9.48683298],
       [  4.        ,   4.12310563,   4.47213595,   5.        ,
          5.65685425,   6.40312424,   7.21110255,   8.06225775,
          8.94427191,   9.8488578 ],
       [  5.        ,   5.09901951,   5.38516481,   5.83095189,
          6.40312424,   7.07106781,   7.81024968,   8.60232527,
          9.43398113,  10.29563014],
       [  

## Fancy Indexing
Indexes for `numpy` arrays can be more than simple numbers and slices.

In [26]:
G = np.arange(10) - 5
G

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [27]:
M = G > 0 # This creates a boolean array. It can be used as a mask.
M

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [28]:
G[M] # This picks only the elements, for which the mask is True.
# Very easy way to filter data.

array([1, 2, 3, 4])

In [29]:
G[[2,7]] # Pick only few indices using a list or array as the index.

array([-3,  2])

All this also works on multiple dimensions.